version: "3.9"

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: docker.io/postgres
    command: "-c max_connections=1000"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./makedb.sh:/docker-entrypoint-initdb.d/makedb.sh:z
    ports:
      - "5432:5432"
  kafka:
    image: docker.io/landoop/fast-data-dev
    environment:
      - ADV_HOST=localhost
      - SAMPLEDATA=1
      - RUNNING_SAMPLEDATA=1
      - RUNTESTS=0
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9092:9092"
      - "9581-9585:9581-9585"
      - "29092:29092"